### ISSUE TITLE
ClassNotFoundException: com.tencent.mm.loader.BuildConfig

### ISSUE THREAD

**Issue by VxTeemo** [Xposed-Modules-Repo/com.fkzhang.wechatxposed#19]
Hello，我在以下环境使用时模块无法生效，请开发者帮忙分析一下，谢谢。

手机型号：Oneplus 7 Pro
系统版本：Oxygen OS 11.0.3.1.GM21AA (Android 11)
Magisk version：25.2 (25200)
LSPosed：v1.8.4 (6609) - Zygisk (API version 93)
微X模块 2.31_4.22 (8,130) p
微信版本：8.0.24_2167 {64bit} <PLAY> (0x28001843)[ec8ca108]

报错：
`de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.tencent.mm.loader.BuildConfig`

模块完整log：
```
[ 2022-09-29T10:24:42.417    10243: 10250: 10250 I/LSPosed-Bridge  ] Loading module com.fkzhang.wechatxposed from /data/app/~~1BD5iBbCtcfyDcCIPm-xPg==/com.fkzhang.wechatxposed-DcCicEhwnoV-Q7VwDMgxoQ==/base.apk
[ 2022-09-29T10:24:42.427    10243: 10250: 10250 I/LSPosed-Bridge  ]   Loading class com.fkzhang.wechatxposed.XposedInit
[ 2022-09-29T10:24:43.417    10243: 10250: 10250 I/LSPosed-Bridge  ] com.tencent.mm loading com.fkzhang.wechatxposed
[ 2022-09-29T10:24:44.993    10243: 10250: 10250 I/LSPosed-Bridge  ] com.fkzhang.wechatxposed [WechatXposed](2.31|95): wechat version 8.0.24(2167)
[ 2022-09-29T10:24:44.993    10243: 10250: 10250 I/LSPosed-Bridge  ] com.fkzhang.wechatxposed load time: 1593
[ 2022-09-29T10:24:45.064    10243: 10250: 10322 I/LSPosed-Bridge  ] 微X模块 2.31_4.22 (8,130) p
[ 2022-09-29T10:24:45.075    10243: 10250: 10322 E/LSPosed-Bridge  ] de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.tencent.mm.loader.BuildConfig
	at de.robv.android.xposed.XposedHelpers.findClass(Unknown Source:12)
	at ˆʾ.ˊˉ.ٴﹳ(Unknown Source:19)
	at ˊˉ.ˎﾞ.ᵢʼ(Unknown Source:32)
	at ˊˉ.ˎﾞ.ⁱˑ(Unknown Source:145)
	at ᐧˑ.ﾞˋ.ﹶˏ(Unknown Source:225)
	at ᐧˑ.ﾞˋ.ʻˋ(Unknown Source:0)
	at ᐧˑ.יʾ.run(Unknown Source:2)
	at ˆʾ.ˆʾ$ˋᐧ.ˋᐧ(Unknown Source:2)
	at ˆʾ.ˆʾ$ˋᐧ.doInBackground(Unknown Source:2)
	at android.os.AsyncTask$3.call(AsyncTask.java:394)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at f03.g.run(SourceFile:38)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at yz2.c.run(SourceFile:1)
	at java.lang.Thread.run(Thread.java:923)
Caused by: java.lang.ClassNotFoundException: com.tencent.mm.loader.BuildConfig
	at java.lang.Class.classForName(Native Method)
	at java.lang.Class.forName(Class.java:454)
	at o.a(Unknown Source:20)
	at de.robv.android.xposed.XposedHelpers.findClass(Unknown Source:4)
	... 18 more
Caused by: java.lang.ClassNotFoundException: com.tencent.mm.loader.BuildConfig
	... 22 more
[ 2022-09-29T10:24:45.076    10243: 10250: 10322 I/LSPosed-Bridge  ] Wechat: 8.0.24_2167 {64bit} <PLAY> (0x28001843)[ec8ca108]
[ 2022-09-29T10:24:45.282    10243: 10250: 10321 I/LSPosed-Bridge  ] feature loaded: base 326
[ 2022-09-29T10:24:46.456    10243: 10469: 10469 I/LSPosed-Bridge  ] Loading module com.fkzhang.wechatxposed from /data/app/~~1BD5iBbCtcfyDcCIPm-xPg==/com.fkzhang.wechatxposed-DcCicEhwnoV-Q7VwDMgxoQ==/base.apk
[ 2022-09-29T10:24:46.468    10243: 10469: 10469 I/LSPosed-Bridge  ]   Loading class com.fkzhang.wechatxposed.XposedInit
[ 2022-09-29T10:24:48.369    10243: 10648: 10648 I/LSPosed-Bridge  ] Loading module com.fkzhang.wechatxposed from /data/app/~~1BD5iBbCtcfyDcCIPm-xPg==/com.fkzhang.wechatxposed-DcCicEhwnoV-Q7VwDMgxoQ==/base.apk
[ 2022-09-29T10:24:48.381    10243: 10648: 10648 I/LSPosed-Bridge  ]   Loading class com.fkzhang.wechatxposed.XposedInit
[ 2022-09-29T10:24:48.860    10243: 10724: 10724 I/LSPosed-Bridge  ] Loading module com.fkzhang.wechatxposed from /data/app/~~1BD5iBbCtcfyDcCIPm-xPg==/com.fkzhang.wechatxposed-DcCicEhwnoV-Q7VwDMgxoQ==/base.apk
[ 2022-09-29T10:24:48.878    10243: 10724: 10724 I/LSPosed-Bridge  ]   Loading class com.fkzhang.wechatxposed.XposedInit
[ 2022-09-29T10:25:08.047    10305: 12747: 12747 I/LSPosed-Bridge  ] Loading module ru.eyrbggXe.ZKdLsoUrO from /data/app/~~IKE2pVV5ViIdPA_lw7hkPQ==/ru.eyrbggXe.ZKdLsoUrO-14E-iOrxQguIz6tSJ9qZQA==/base.apk
[ 2022-09-29T10:25:08.084    10305: 12747: 12747 I/LSPosed-Bridge  ]   Loading class com.xposed.XSupport
[ 2022-09-29T10:25:08.695    10243: 10250: 10321 E/LSPosed-Bridge  ] de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.tencent.mm.loader.BuildConfig
	at de.robv.android.xposed.XposedHelpers.findClass(Unknown Source:12)
	at ˆʾ.ˊˉ.ٴﹳ(Unknown Source:19)
	at ˊˉ.ˎﾞ.ᵢʼ(Unknown Source:32)
	at ˊˉ.ˎﾞ.ⁱˑ(Unknown Source:145)
	at ˊˉ.ᵔᴵ.ــ(Unknown Source:1247)
	at ˊˉ.ᵔᴵ.ˎˑ(Unknown Source:94)
	at ˊˉ.ᵔᴵ.ˑᐧ(Unknown Source:1)
	at ˊˉ.ᵔᴵ.ﹳʾ(Unknown Source:3)
	at ˊˉ.ᵔᴵ.יˉ(Unknown Source:1)
	at ˊˉ.ᵔᴵ.ʾʻ(Unknown Source:0)
	at ˊˉ.ˊﹶ.run(Unknown Source:2)
	at ˆʾ.ˆʾ.ﹳʻ(Unknown Source:0)
	at ˆʾ.ˆʾ.ﾞˑ(Unknown Source:0)
	at ˆʾ.ᵢˈ.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:233)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: java.lang.ClassNotFoundException: com.tencent.mm.loader.BuildConfig
	at java.lang.Class.classForName(Native Method)
	at java.lang.Class.forName(Class.java:454)
	at o.a(Unknown Source:20)
	at de.robv.android.xposed.XposedHelpers.findClass(Unknown Source:4)
	... 17 more
Caused by: java.lang.ClassNotFoundException: com.tencent.mm.loader.BuildConfig
	... 21 more
[ 2022-09-29T10:25:38.962    10243: 10250: 10250 E/LSPosed-Bridge  ] java.lang.NoSuchMethodError: com.tencent.mm.ui.base.preference.Preference#setTitle(java.lang.String)
	at de.robv.android.xposed.XposedHelpers.lambda$findMethodBestMatch$5(Unknown Source:6)
	at de.robv.android.xposed.XposedHelpers.f(Unknown Source:0)
	at de.robv.android.xposed.c.get(Unknown Source:8)
	at java.util.Optional.orElseThrow(Optional.java:286)
	at de.robv.android.xposed.XposedHelpers.findMethodBestMatch(Unknown Source:26)
	at de.robv.android.xposed.XposedHelpers.findMethodBestMatch(Unknown Source:4)
	at de.robv.android.xposed.XposedHelpers.callMethod(Unknown Source:4)
	at ᐧˑ.ﾞˋ$ˋⁱ.afterHookedMethod(Unknown Source:512)
	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:147)
	at LSPHooker_.onCreate(Unknown Source:11)
	at com.tencent.mm.ui.vas.VASActivity.onCreate(SourceFile:2)
	at java.lang.reflect.Method.invoke(Native Method)
	at androidx.lifecycle.b$a.a(SourceFile:6)
	at androidx.lifecycle.ReflectiveGenericLifecycleObserver.u0(SourceFile:2)
	at androidx.lifecycle.r$a.a(SourceFile:3)
	at androidx.lifecycle.r.addObserver(SourceFile:13)
	at com.tencent.mm.ui.vas.VASCommonFragment.onViewCreated(SourceFile:10)
	at androidx.fragment.app.Fragment.performViewCreated(SourceFile:1)
	at androidx.fragment.app.b0.f(SourceFile:38)
	at androidx.fragment.app.b0.k(SourceFile:23)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(SourceFile:68)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(SourceFile:11)
	at androidx.fragment.app.FragmentManager.execPendingActions(SourceFile:4)
	at androidx.fragment.app.FragmentManager$g.run(Unknown Source:3)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:233)
	at android.app.ActivityThread.main(ActivityThread.java:8010)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)

```

如果需要全部的LSPosed日志请联系

**Comment by VxTeemo** [comment]
其他hook微信的模块是可以生效的，比如fingerprint-pay指纹支付的模块

**Comment by VxTeemo** [comment]
从tg群了解到已经适配，问题关闭了
